// Generated by scripts/record-presets.ts. Do not edit by hand.
import r0 from './citation-check__contradicted.json'
import r1 from './citation-check__supported.json'
import r2 from './citation-check__unsupported-iat.json'
import r3 from './citation-check__unsupported-pii.json'
import r4 from './date-extraction__contract-two-dates.json'
import r5 from './date-extraction__form-deadline.json'
import r6 from './date-extraction__never-mentioned.json'
import r7 from './date-extraction__next-thursday.json'
import r8 from './first-run__resolved.json'
import r9 from './limit-counting__breaks.json'
import r10 from './limit-counting__works.json'
import r11 from './limit-dates__breaks.json'
import r12 from './limit-dates__works.json'
import r13 from './limit-injected-state__breaks.json'
import r14 from './limit-injected-state__works.json'
import r15 from './model-routing__late-order-complaint.json'
import r16 from './model-routing__order-lookup.json'
import r17 from './model-routing__product-fit.json'
import r18 from './smart-home__compound.json'
import r19 from './smart-home__dim-to-thirty.json'
import r20 from './smart-home__lights-off-house.json'
import r21 from './smart-home__weather.json'
import r22 from './support-triage__angry.json'
import r23 from './support-triage__distracting.json'
import r24 from './voice-banking__balance.json'
import r25 from './voice-banking__fraud.json'
import r26 from './voice-banking__self-interrupted.json'
import r27 from './voice-banking__transfer.json'

export interface OwnRecording {
  preset: string
  variant: string
  recordedAt: string
  model: string
  request: { state: unknown; model: string; questions: Record<string, unknown> }
  answers: Record<string, unknown>
  usage: { input_tokens: number; output_tokens: number }
}

export const OWN_RECORDINGS: OwnRecording[] = [r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12, r13, r14, r15, r16, r17, r18, r19, r20, r21, r22, r23, r24, r25, r26, r27] as OwnRecording[]
